version: '3.4'
services:
  mongo-express:
    image: mongo-express
    container_name: terrible-mongo-express
    ports:
      - 9000:8081
    links:
      - mongo

  mongo:
    image: mongo
    container_name: terrible-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  elastic:
    image: elasticsearch:7.6.1
    container_name: terrible-search
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/dat
    ports:
      - "9200:9200"
      - "9300:9300"

  grafana:
    image: "grafana/grafana"
    container_name: terrible-grafana
    ports:
      - "3000:3000"
    network_mode: host
 
  prometheus:
    image: "prom/prometheus"
    container_name: terrible-prometheus
    ports:
       - "9090:9090"
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host

volumes:
  mongo-data:
  elastic-data:
