global:
  scrape_interval:     5s 
  evaluation_interval: 5s
  
scrape_configs:
  - job_name: 'terrible-api-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['localhost:8081']
