spring:
  application:
    name: terrible-api-service

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

search:
  scheme: "http"
  host: "localhost"
  port: 9200

---
spring:
  profiles: production
  data:
    mongodb:
      host: terrible-mongo
  webflux:
    base-path: /api

search:
  scheme: "http"
  host: "terrible-search"
  port: 9200
