spring:
  application:
    name: terrible-api-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

---
spring:
  profiles: production
  data:
    mongodb:
      host: terrible-mongo
  webflux:
    base-path: /api
