spring:
  application:
    name: terrible-api-service
  batch:
    job:
      enabled: false

server:
  port: 8081

terrible:
  index: media
  thumbnailJob: true
  directoryJob: true
  search-service:
    scheme: http
    host: localhost
    port: 8082

batch:
  delay: 60000 #milliseconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
